routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\IndexController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::name('user.')->prefix('user')->group(function () {
    Auth::routes();
});

Route::name('admin.')
    ->prefix('admin')
    ->namespace('Admin')
    ->middleware('auth')
    ->group(function () {
        // головна сторінка панелі керування
        Route::get('', [IndexController::class, 'index'])->name('index');
        // CRUD-операції над користувачами: admin.users.index,admin.users.edit, admin.users.create і т.д.
        Route::resource("users", 'UserController');
    });

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',

    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];





}

app/Http/Controllers/Admin/IndexController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class IndexController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
//        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
            return view('admin.index');
    }


}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserUpdateRequest;
use App\Models\User;
use Illuminate\Http\Request;

//use Illuminate\Database\Eloquent\Collection;
//use Illuminate\Support\Facades\Auth;
//use Illuminate\Support\Facades\DB;
//use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application| \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::where('id','!=',auth()->id())
                 ->paginate(5);

        return view('admin.users.index', compact('users'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    /**
     * Create a new user instance after a valid registration.
     *
     * @param array $data
     * @return User|\Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    protected function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        // 1-й спосіб ВИКОРИСТАННЯ СТАНДАРТНОГО ОБЄКТА Validator
        Validator::make($request->all(), [
            'name' => 'required',
            'password' => 'required|min:5',
            'email' => 'required|email|unique:users',
        ],
        )->validate();

        $data = $request->all();
        $data['password'] = Hash::make($data['password']);
        $result = User::create($data);

        if ($result) {
            return redirect()->route('admin.users.index')
                ->with(['success' => 'Успішно збережено']);
        } else {
            return back()
                ->withErrors(['msg' => 'Помилка при зберіганні!'])
                ->withInput();
        }
    }


    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function show($id)
    {
        $users = User::find($id);
        return view('admin.users.index', compact('users'));
    }


    /**
     * Показує форму для редагування користувача - доступ за id
     *
     * @param \App\Models\User $user
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public
    function edit(int $id)
    {
        // приклад використання ORM моделі
        $user = User::find($id);
        return view('admin.users.edit', compact('user'));
    }

//    /** АБО так можна:
//     * Show the form for editing the specified resource.
//     * Використання моделі роботи з БД ORM, обєкт User, як параметр
//     * @param  User  $user
//     * @return \Illuminate\Http\Response
//     */
//    public function edit(User $user)
//    {
//        return view('admin.users.edit', compact('user'));
//    }


    /**
     * Оновлення даних користувача за його id
     * ORM
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public
    function update(UserUpdateRequest $request, int $id)
    {   //2-й спосіб валідації використовуємо App\Http\Requests\UserUpdateRequest

        /*закоментовано 3-й спосіб
        $rules=[
             'name' => 'required',
             'password' => 'required|min:5',
             'email' => 'required|email|exists:users,email',
         ];
        $validator=Validator::make($request->all(),$rules)->validate();
        */
        $user = User::find($id);
        if (empty($user)) {
            return back()
                ->withErrors(['msg' => "Користувач з id=[{$id}] не знайдена!"])
                ->withInput();
        }

        $data = $request->all();
        $data['password'] = Hash::make($data['password']);
        $result = $user->fill($data)->save();

        if ($result) {
            return redirect()->route('admin.users.index')
                ->with(['success' => 'Успішно збережено']);
        } else {
            return back()
                ->withErrors(['msg' => 'Помилка при зберіганні!'])
                ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     * Видалення ORM
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public
    function destroy(User $user)
    {
        $user->delete();
        return redirect()
            ->route('admin.users.index')
            ->with('success', 'Користувач видалений');
    }


}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/admin/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('AdminPanel') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                         {{ __('Welcome to AdminPanel!') }} {{ strtoupper(auth()->user()->name) }} :)
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'ADMINKA') }}</title>
    <link rel="apple-touch-icon" sizes="76x76" href="{{ asset('assetsAdmin/img/apple-icon.png') }}">
    <link rel="icon" type="image/png" href="{{ asset('assetsAdmin/img/favicon.ico') }}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <title>Admin pannel</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
          name='viewport'/>
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"/>
    <!-- CSS Files -->
    <link href="{{ asset('assetsAdmin/css/bootstrap.min.css') }}" rel="stylesheet"/>
    <link href='{{ asset("assetsAdmin/css/light-bootstrap-dashboard.css?v=2.0.0") }}'rel="stylesheet"/>
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="{{ asset('assetsAdmin/css/demo.css') }}" rel="stylesheet"/>
    <link rel="shortcut icon" href="{{ asset('favicon.ico') }}">

</head>
<body>

<div class="wrapper">
    <div class="sidebar" data-image="{{ asset('assetsAdmin/img/sidebar-4.jpg')}}">
        <div class="sidebar-wrapper">
            <div class="logo">
                <a href="{{route('home')}}" class="simple-text">
                    Test-Task-Laravel
                </a>
            </div>
            @include('admin.layouts.nav')
        </div>
    </div>
    <div class="main-panel">
        <div class="content">
            <div id="app">
                <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
                    <div class="container">
                        <a class="navbar-brand" href="{{ url('/') }}">
                            {{ config('app.name', 'Laravel') }}
                        </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <!-- Left Side Of Navbar -->
                            <ul class="navbar-nav mr-auto">

                            </ul>

                            <!-- Right Side Of Navbar -->
                            <ul class="navbar-nav ml-auto">
                                <!-- Authentication Links -->



                                    <li class="nav-item dropdown">
                                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                            {{ \Illuminate\Support\Facades\Auth::user()->name}}
                                        </a>

                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="{{ route('user.logout') }}"
                                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                                {{ __('Logout') }}
                                            </a>

                                            <form id="logout-form" action="{{ route('user.logout') }}" method="POST"
                                                  class="d-none">
                                                @csrf
                                            </form>
                                        </div>
                                    </li>

                            </ul>
                        </div>
                    </div>
                </nav>

                <main class="py-4">
                    @yield('content')
                </main>
            </div>
        </div>
    </div>
</div>

</body>
<!--   Core JS Files   -->
<script src="{{ asset('assetsAdmin/js/core/jquery.3.2.1.min.js') }}" type="text/javascript"></script>
<script src="{{asset('assetsAdmin/js/core/popper.min.js')}}" type="text/javascript"></script>
<script src="{{asset('assetsAdmin/js/core/bootstrap.min.js')}}" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{{asset('assetsAdmin/js/plugins/bootstrap-switch.js')}}"></script>
<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!--  Chartist Plugin  -->
<script src="{{asset('assetsAdmin/js/plugins/chartist.min.js')}}"></script>
<!--  Notifications Plugin    -->
<script src="{{asset('assetsAdmin/js/plugins/bootstrap-notify.js')}}"></script>
<!-- Control Center for Light Bootstrap Dashboard: scripts for the example pages etc -->
<script src="{{asset('assetsAdmin/js/light-bootstrap-dashboard.js?v=2.0.0')}} " type="text/javascript"></script>
<!-- Light Bootstrap Dashboard DEMO methods, don't include it in your project! -->
<script src="{{asset('assetsAdmin/js/demo.js')}}"></script>


</html>

resources/views/admin/layouts/nav.blade.php
<ul class="nav">
    <li class="nav-item ">
        <a class="nav-link" href="{{route('admin.index')}}">
            <i class="nc-icon nc-chart-pie-35"></i>
            <p>Info</p>
        </a>
    </li>
    <li class="nav-item ">
        <a class="nav-link"
           href="{{route('admin.users.index')}}"
        >
            <i class="nc-icon nc-circle-09"></i>
            <p>All Users</p>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{route('admin.users.create')}}">
            <i class="nc-icon nc-simple-add"></i>
            <p>Add New Users</p>
        </a>
    </li>
    <li>

        <a class="nav-link" href="{{ route('user.logout') }}"
           onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
            <i class="nc-icon nc-key-25"></i>
            <p>Log out</p>
        </a>
    </li>
</ul>

resources/views/admin/users/create.blade.php
@extends('admin.layouts.app')

@section('content')
    @php
        /**
        * {{-- * @var \App\Models\User $user--}}
        */
    @endphp
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('admin.index') }}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page"><a href="{{ route('admin.users.index') }}">Users</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page"> Create user</li>
        </ol>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Edit User</h4>
                        @if(session('success'))
                            <div class="row justify-content-center">
                                <div class="col-md-11">
                                    <div class="alert alert-danger" role="alert">
                                        {{session()->get('success')}}
                                    </div>
                                </div>
                            </div>
                        @endif
                        @if($errors->any())
                            <div class="row justify-content-center">
                                <div class="col-md-11">
                                    <div class="alert alert-danger" role="alert">
                                        @foreach($errors->all() as $error)
                                            <p>{{ $error }}</p>
                                        @endforeach

                                    </div>
                                </div>
                            </div>
                        @endif
                    </div>
                    <div class="card-body">

                        <form id="form" method="POST" action="{{ route('admin.users.store') }}">
                            @csrf
                            @method('POST')
                            <div class="form-group">
                                <label>id (disabled)</label>
                                <input type="text" class="form-control"
                                       name="id"
                                       value=""
                                       disabled placeholder="id">
                            </div>

                            <div class="form-group">
                                <label> Name </label>
                                <input type="text" class="form-control"
                                       name="name" placeholder="UserName"
                                       class="form-control @error('name') is-invalid @enderror"
                                       value="{{old('name')}}">

                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label>Email </label>
                                <input type="text" class="form-control"
                                       name="email" placeholder="login@gamil.com"
                                       class="form-control @error('email') is-invalid @enderror"
                                       value="{{old('email')}}">

                                @error('email')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label> Password </label>
                                <input type="text" class="form-control"
                                       name="password" placeholder="password"
                                       class="form-control @error('password') is-invalid @enderror"
                                       value="{{old('password')}}">

                                @error('password')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <button type="submit" name="save_user" class="btn btn-primary btn-fill pull-right">Save
                            </button>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>

@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    @php
        /**
        * {{-- * @var \App\Models\User $user--}}
        * {{-- * @var \Illuminate\Support\Collection $userList--}}
         * */
    @endphp
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('admin.index') }}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page"><a href="{{ route('admin.users.index') }}">Users</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">  {{ $user->name }}</li>
        </ol>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Edit User</h4>
                        @if($errors->any())
                        <div class="row justify-content-center">
                            <div class="col-md-11">
                                <div class="alert alert-danger" role="alert">
                                        @foreach($errors->all() as $error)
                                            <p>{{ $error }}</p>
                                        @endforeach

                                </div>
                            </div>
                        </div>
                        @endif
                    </div>

                    <div class="card-body">
                        <form id="form" method="POST" action="{{route('admin.users.update',$user->id) }}">
                            @method('PATCH') {{-- щоб розпізнав post як patch--}}
{{--                            @csrf  --}}{{--директива для захисту форм від хакерських атак, можна звичайно створити білий список --}}
                            {{ @csrf_field() }}
                            <div class="form-group">
                                <label>id (disabled)</label>
                                <input type="text" class="form-control"
                                       name="id"
                                       value="{{$user->id}}"
                                       disabled placeholder="id">

                            </div>

                            <div class="form-group">
                                <label> Name </label>
                                <input type="text" class="form-control"
                                       name="name" placeholder="Name"
                                       class="form-control"
                                       value="{{ $user->name }}">

                            </div>

                            <div class="form-group">
                                <label>Email </label>
                                <input type="text" class="form-control"
                                       name="email" placeholder="login@gamil.com"
                                       class="form-control"
                                       value="{{ $user->email }}">

                            </div>

                            <div class="form-group">
                                <label> Password </label>
                                <input type="text" class="form-control"
                                       name="password" placeholder="password"
                                       class="form-control"
                                       value="{{ $user->password }}">

                            </div>

                            <button type="submit" name="save_user" class="btn btn-primary btn-fill pull-right">Save
                            </button>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>

@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ asset('admin.index') }}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">
                                Users
                            </li>

                        </ol>
                    </nav>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="card strpied-tabled-with-hover">
                                    <div class="card-header ">
                                        <h4 class="card-title">Users </h4>
                                        <p class="card-category">

                                        </p>
                                    </div>
                                    <div class="card-body table-full-width table-responsive">
                                        <table class="table table-hover table-striped">
                                            <thead>
                                            <th>ID</th>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Password</th>
                                            <th>Options</th>
                                            </thead>
                                            <tbody>
                                            @foreach($users  as $user)
                                                 @php /** @var App\Models\User $user */ @endphp
{{--                                                @if ($user->id == auth()->id())--}}
{{--                                                    @continue--}}
{{--                                                @endif--}}
                                                <tr>
                                                    <td>{{$user->id}}</td>
                                                    <td>
                                                        <a href="#">
                                                            {{$user->name}}
                                                        </a>
                                                    </td>
                                                    <td>
                                                        {{$user->email}}
                                                    </td>
                                                    <td>
                                                        {{$user->password}}
                                                    </td>
                                                    <td>
                                                        <a href="{{ route('admin.users.edit', ['user' => $user->id]) }}">
                                                            {{--                                                            <i class="glyphicon glyphicon-edit"></i>--}}
                                                            <img
                                                                src="{{ asset('assetsAdmin/img/button/user-edit-icon.png')}}">

                                                        </a>
                                                        <form action="{{ route('admin.users.destroy', $user) }}"
                                                              method="post"
                                                              onsubmit="return confirm('Видалити цього користувача?')">
                                                            @csrf
                                                            @method('DELETE')
                                                            <button type="submit"
                                                                    class="m-0 p-0 border-0 bg-transparent">
                                                                <img
                                                                    src="{{ asset('assetsAdmin/img/button/user-delete-icon.png')}}">

                                                            </button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach

                                            </tbody>

                                        </table>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>
                    @if($users->total()>=$users->count())
                        <br>
                        <div class="row justify-content-center">
                            {{$users->links("pagination::bootstrap-4")}}
                        </div>
                    @endif


                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><h1>{{ __('My Cabinet') }}</h1></div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                         <p> Ласкаво просимо, {{ auth()->user()->name }}</p>
                        <p> Це ваш особистий акаунт користувача.</p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection